signeer/signeer/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin

urlpatterns = [
    url(r'^', include('tshirt.urls')),
    url(r'^admin/', admin.site.urls),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

signeer/tshirt/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from .import views



app_name='tshirt'
urlpatterns = [
    url(r'^$', views.detail, name='detail'),

   #url(r'^rest/$', views.rest_query, name='rest_query'),
    url(r'^upload_file', views.upload_file, name='upload_file'),

    #stocks/
    url(r'^serilization/', views.post_serilization, name= 'serilization')

]
urlpatterns = format_suffix_patterns(urlpatterns)

signeer/tshirt/models.py
from django.db import models
from django.forms import forms
import os
# Create your models here.

class VendorPost(models.Model):
    id = models.AutoField(primary_key=True)
    text =models.CharField(max_length =500)
    data = models.CharField(max_length =100)
    picture = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.text

signeer/tshirt/forms.py
from django.forms import ModelForm
from .models import VendorPost



class TshirtForm(ModelForm):

    class Meta:
        model =VendorPost
        fields=('id','text','data','picture')
    

signeer/tshirt/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.shortcuts import get_list_or_404
from rest_framework.views import APIView
from rest_framework.response import  responses
from rest_framework import status
from django.conf import settings



from.models import VendorPost
from.forms import TshirtForm
from . serializers import VendorPost_Serializer
# Create your views here.


def upload_file (request):

    #posts = VendorPost.objects.all()
    form=TshirtForm(request.POST, request.FILES)
    if form.is_valid():
        instance=form.save(commit=False)
        instance.save()
        print form.cleaned_data.get("text")


    #if request.method=="POST":
        #print request.POST.get("text")
        #print request.POST.get("data")
        #print request.POST.get("picture")
        #print request.POST.get("id")
    context ={'form':form}
    return render(request,'tshirt/upload_file.html', context)


def detail(request):
    #data_form=TshirtForm()
    data_form=VendorPost.objects.all()
    return render(request,'tshirt/detail.html',{'data_form': data_form, 'media_url': settings.MEDIA_URL})
   #<!-------------------NOW Start RESTFRAMEWORK---------------------------->



# serilization/
def  post_serilization(APIView):

    def get(self, request,format=None):
        vendor_obj =VendorPost.objects.all()
        serializers =VendorPost_Serializer(vendor_obj, many =True)
        return responses(serializers.data)

signeer/tshirt/templates/tshirt/detail.html
{% extends 'bootstrap3/bootstrap3.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

<!DOCTYPE html>

<html>

  <head>
        <title>{% block bootstrap3_title %}Entered Data{% endblock %}</title>

  </head>
<body>
  {% block bootstrap3_content %}

  <h2 class="text-center">Tshirt Data</h2>
  <div class ="container">
    <!-----------------Search Bar-------->

    <form id="searchform" action="{% url 'tshirt:upload_file' %}" method="post">
              {% csrf_token %}
      <div class ="container">

            <div class="wrap">
                  <div class="search">
                        <input type="text" class="searchTerm" placeholder="What are you looking for?">
                            <button type="submit" class="searchButton" action="{% url 'tshirt:upload_file' %}">
                              Search
                            </button>
                          </div>
            </div>
      </div>

      </form>
  </div>
<!------------------Data UPload TO User Page---------->
<div class="container">
  <table class="table table-stripped">
{% block bootstrap_css %}
  <tr>
    <th>id</th>
    <th>Text</th>
    <th>Data</th>
    <th>Picture</th>
  </tr>
  <tr>
      {% for value in data_form %}
    <td>{{ value.id }}</td>
    <td>{{ value.text }}</td>
    <td>{{ value.data}}</td>
      <td>
<!-----------Adding MEDIA_URL for images upload or downlaod foler path-------->
        <img class="iimg-circle" src="{{media_url}}{{value.picture}}"></td>
  </tr>

  {% endfor %}
  {%endblock%}
</div>
{%endblock%}
</body>


</html>

signeer/tshirt/templates/tshirt/rest_query.html
{% extends 'bootstrap3/bootstrap3.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

<!DOCTYPE html>

<html>

  <head>
        <title>{% block bootstrap3_title %}Entered Data{% endblock %}</title>
      {% for value in documents%}
    {{ value.id }}
    {{ value.text }}
    {{ value.data}}
  </head>
<body>


</body>


</html>

signeer/tshirt/templates/tshirt/upload_file.html
{% extends 'bootstrap3/bootstrap3.html' %}
{% load bootstrap3 %}
{% load static %}
<!DOCTYPE html>

<html>

  <head>
        <title>{% block bootstrap3_title %}Welcome To Tshirt {% endblock %}</title>

  </head>
<body>

  {% block bootstrap3_content %}
  <div class="container">

  <h2>Welcome To Tshirt </h2>

  <form class="formdata" action="{% url 'tshirt:upload_file' %}" method="post" enctype="multipart/form-data">

    {% csrf_token %}
    {% bootstrap_form form  %}
    <!-----Adding Star into uppers-------->
    {% bootstrap_icon "star" %}
    <!------submit button-------->
    {% buttons submit='Check' %}
    {% endbuttons %}

  </form>
</div>


  {% endblock %}

</body>


</html>