mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^tshirt/', include('tshirt.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/tshirt/urls.py
from django.conf.urls import url

from . import views

app_name='tshirt'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)$', views.DetailView.as_view(), name = 'detail'),


]

mysite/polls/models.py
from django.utils import timezone
import datetime
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
def was_published_recently(self):
    now = timezone.now()
    return now - datetime(days=1)<=self.pub_date <= now

mysite/tshirt/models.py
from __future__ import unicode_literals
from django.utils.encoding import smart_unicode
from django.core.urlresolvers import reverse

from django.db import models


class VendorPost(models.Model):
    id = models.IntegerField(primary_key=True)
    text =models.CharField(max_length =500)
    data = models.CharField(max_length =100)
    picture = models.ImageField(upload_to='tshirt')

    def __unicode__(self):
        return smart_unicode(self.id)

mysite/tshirt/forms.py
from django import forms
from.models import VendorPost


class ShirtForm(forms.ModelForm):
    id = models.IntegerField(primary_key=True)
    text =models.CharField(max_length =500)
    data = models.CharField(max_length =100)
    picture = models.ImageField(upload_to='tshirt')

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from django.utils import timezone
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions (not including those
        set to bepublished in the future)"""
        return Question.objects.filter(
        pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Exclude any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte= timezone.nw())



class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
        question = get_object_or_404(question,pk = question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, choice.DoesNotExist):
            return render (request,'polls/detail.html',{'question': question, 'error_message':"you didn't select a choice"})
        else:
            selected_choice.votes +=1
            selected_choice.save()
            return HttpResponseRedirect(reverse('polls:results', args= (question.id,)))

mysite/tshirt/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .forms import ShirtForm

# Create your views here.
from.models import VendorPost
class IndexView(generic.ListView):
    form=ShirtForm()
    context={'myregistrationform':form}
    template_name='tshirt/form.html'
    context_object_name='all_data'
    def get_queryset(self):
        return VendorPost.objects.all()

class DetailView(generic.DetailView):
    model=VendorPost
    template_name='tshirt/detail.html'

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
  <ul>
    {%for question in latest_question_list%}
  <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
  </ul>
{%else %}
  <p> No polls are Available.</p>

  {%endif%}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/tshirt/templates/tshirt/detail.html
<title>Detail Page</title>

<img src ="{{ shirt.shirt.picture }}" >

<h1>{{ shirt.shirt.id }}</h1>
<h3>{{ shirt.shirt.text }}</h3>

{% if error_message%}
  <p><strong>{{error_message}}</strong></p>
{%endif%}


{%endblock%}

mysite/tshirt/templates/tshirt/form.html
<!DOCTYPE html>
<html>
<head>


</head>

<body>
<h1>WellCome To Shirt<h1>
  <form method='post' action=''>
    <input type ='text'>
        {{form.as_p}}
        
    <input type='submit'>

</form>
</body>



</html>

mysite/tshirt/templates/tshirt/index.html
<h1>Wellcome TShirt Store</h1>
    <ul>

          {% for shirt in all_data %}
          <li><a href = "{% url 'tshirt:detail' shirt.id %}">{{ shirt.shirt.id}}</a></li>
          {% endfor %}
      </ul>