mywebsite/music/urls.py
from django.conf.urls import url
from . import views

app_name='music'

urlpatterns = [
    #/music/
    url(r'^$', views.IndexView.as_view(), name = 'index'),

    url(r'^(?P<pk>[0-9]+)$', views.DetailView.as_view(), name = 'detail'),

        # /music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name = 'album-add'),

    # /music/album/Update/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name = 'album-update'),

    # /music/album/Delet
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelet.as_view(), name ='album-delete'),


    #/music/falbum_id/Favorite/
    #url(r'^(?P<album_id>[0-9]+)$', views.favorite, name = 'favorite'),

]

mywebsite/mywebsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

mywebsite/music/models.py
from django.db import models
from django.core.urlresolvers import reverse








# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title =models.CharField(max_length =500)
    genre = models.CharField(max_length =100)
    album_logo =models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music/detail',kwargs={'pk':self.pk})

    def __str__(self):
          return self.album_title + ' - '+ self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length =250)
    is_favorite =models.BooleanField(default= False)


    def __str__(self):
        return self.song_title

mywebsite/music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Album


class IndexView(generic.ListView): #generic views
    template_name='music/index.html'
    context_object_name='all_albums '

    def get_queryset(self):
        return Album.objects.all()



class DetailView(generic.DeleteView):
    model=Album
    template_name= 'music/detail.html'


class AlbumCreate(CreateView):
    model =Album
    fields=['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model =Album
    fields=['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelet(DeleteView):
    model=Album
    success_url= reverse_lazy('music:index')

mywebsite/music/templates/music/album_form.html
<!---Loads the Path to your static files----->
{%extends 'music/base.html'%}
{%block title%}
<title>Add a New Album</title>
{%endblock%}
{%block album_active%}active {%endblock%}


{%block body%}
<div class="container">

        <div class ="col-sm-12 col-md-7">
                <div class="panel panel-default">

                      <div class ="panel-body">
                          <form class="form-horizontal" action ="" method ="post" enctype= "multipart/form-data">
                                {% csrf_token %}
                                {%include 'music/form-template.html'%}
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                      <button type="submit" class ="btn btn-success">Submit</button>
                                    </div>

                                </div>
                            </form>

                        <div>

                </div>


        </div>
</div>
{%endblock%}

mywebsite/music/templates/music/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charest="UTF-8">
  {%block title%}
  <title>Viberr</title>
  {%endblock%}
  {%load staticfiles%}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Satisfy" />
  <link rel = "stylesheet" type="text/css" href ="{%static 'music/style.css'%}"/>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


</head>
<body>
  <nav class="navbar navbar-default">
       <div class="container>
          <button type="button" class="navbar-toggle" data-toggle ="collapse" data-target="#topNavBar">
              <span class ="icone-bar"></span>
              <span class ="icone-bar"></span>
              <span class ="icone-bar"></span>
          </button>

              <div clas="navbar-header">
                      <a class="navbar-brand" href="{% url 'music:index' %}">GKy</a>
              </div>

      <!-----------------------------------Items------------------------->



                <div class ="collapse navbar-collapse"id="topNovBar">


                  <ul>
                      <li class ="active">
                        <a href="{% url 'music:index' %}">
                            <span class ="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;  Albums
                        </a>
                      </li>
                      <li class ="">
                        <a href="{% url 'music:index' %}">
                            <span class ="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;  Songs
                        </a>
                      </li>
                  </ul>

                  <form class ="navbar-form navbar-left" role="search" method="get" action="#">
                      <div class="form-group">
                        <input type="text" class ="form-control" name="q" value="">
                      </div>
                      <button type="submit" class "btn btn-default">Search</button>
                  </form>

                  <ul class ="nav navbar-nav navbar-right">
                    <li class ="">

                      <a href="{%url 'music:album-add'%}">
                          <span class ="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                      </a>
                    </li>

                    <li class ="">
                      <a href="#">
                          <span class ="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;  Logout
                      </a>
                    </li>

                  </ul>

              </div>
      </div>

    </nav>
<!------->

    {%block body%}

    {%endblock%}


</body>
</html>

mywebsite/music/templates/music/detail.html
<!---Loads the Path to your static files----->
{%extends 'music/base.html'%}
{%block title%}
<title>Detail Page</title>
{%endblock%}


{%block body%}
<img src ="{{ album.album_logo }}" >

<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>

{% if error_message%}
  <p><strong>{{error_message}}</strong></p>
{%endif%}


{%endblock%}

mywebsite/music/templates/music/form-template.html
{%for field in form%}

<div class="form-group">

      <div class="col-sm-offset-2 col-sm-10">
            <span class ="text-danger small">
                  {{field.errors}}
            </span>
      </div>
      <label class ="control-label col-sm-2">{{field.label_tag}}</label>
      <div class="col-sm-10">{{field}}</div>

</div>

{%endfor%}

mywebsite/music/templates/music/index.html
<!---Loads the Path to your static files----->
{%extends 'music/base.html' %}


{%block body%}
{% if object_list %}
<h1>Here are all my Albums</h1>
    <ul>

          {% for album in object_list %}
          <li><a href = "{% url 'music:detail' album.id %}">{{ album.album_title}}</a></li>
          {% endfor %}
      </ul>
{% else %}
      <h3> You don't have any album</h3>

{%endif%}
{%endblock%}